### ISSUE TITLE
The engine node is '10.14.2' which is too old to now, please support to upgrade it!

### ISSUE THREAD

**Issue by EliazTray** [jenkey2011/vuepress-deploy#15]

**Comment by mefarazath** [comment]
I faced the same issue when trying to install vuepress with this git action

**Comment by jenkey2011** [comment]
Done!
Now update the node version to v14.16.0
```yml
# use v1.6.1
uses: jenkey2011/vuepress-deploy@1.6.1

# or use branch of master
uses: jenkey2011/vuepress-deploy@master
```
@mefarazath @EliazTray
