### ISSUE TITLE
Last updated does not work when deployed using GitHub Actions

### ISSUE THREAD

**Issue by mihyunLee** [jenkey2011/vuepress-deploy#36]
**Describe the bug**

It works fine when running yarn dev, but it does not work when building with github action.

**Expected behavior**

I would expect that also using the GitHub Action that the "Last updated" value is shown.

**Screenshots**

- dev
<img width="654" alt="image" src="https://github.com/jenkey2011/vuepress-deploy/assets/51310674/8c51f39f-1221-43b5-a4ba-ceb770e1e40e">

- build & deploy
<img width="621" alt="image" src="https://github.com/jenkey2011/vuepress-deploy/assets/51310674/10b94231-29a7-45de-9279-e5b466fbcf76">

**Additional Comments**

> This is main.yml I am using.

```yml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
```
