### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.19.1"

### ISSUE THREAD

**Issue by ben0222** [jenkey2011/vuepress-deploy#38]
**Describe the bug**

The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.19.1"

**Reproduce**
deploy-docs.yml

```
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vuepress deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # TARGET_REPO: username/repo not nesessary
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: blog/.vuepress/dist/
```
**Expected behavior**

Node version >=18

**Screenshots**

![Snipaste_2024-03-07_22-29-26](https://github.com/jenkey2011/vuepress-deploy/assets/129187434/e713231a-06a7-4fbc-805a-dc67bdc83dbd)

**Additional Comments**

Could you update the node version? Thanks!
